//Uncomment this line on creating a translation file
//import { editorLocalization, defaultStrings } from "../editorLocalization";

export var enStrings = {
  "survey": {
    "edit": "编辑",
    "dropQuestion": "请将问题放置此区域",
    "copy": "复制",
    "addToToolbox": "添加到工具箱",
    "deletePanel": "删除面板",
    "deleteQuestion": "删除题目",
    "convertTo": "转变为",
    "drag": "移动题目"
  },
  "qt": {
    "radiogroup": "单项选择题",
    "checkbox": "多项选择题",
    "text": "单项填空题",
    "dropdown": "下拉单选题",
    "file": "文件上传题",
    "imagepicker": "图片选择题",
    "html": "HTML代码",
    "matrix": "单项表格",
    "matrixdropdown": "多项表格",
    "matrixdynamic": "动态表格",
    "multipletext": "多项填空题",
    "tagbox": "下拉多选题",
    "radioinputgroup": "选择填空题",
    "comment": "多行文本题",
    "sortablelist": "拖拽排序题",
    "barrating": "图标评分题",
    "boolean": "是否题",
    "expression": "表达式",
    "microphone": "录音题",
    "editor": "富文本题",
    "nouislider": "刻度评分题",
    "bootstrapslider": "滑块评分题",
    "rating": "分段评分题",
    "panel": "题目面板",
    "paneldynamic": "动态面板",
    "signaturepad": "手写板",
    "selectmutex": "下拉排序题",
    "datepicker": "日期题",
    "multilevellinkage": "级联题",
    "cascader": "级联题",
    "slider": "滑块题",
    "default": "默认"
  },
  "ct": {
    "questiontype": "题型",
    "questionlib": "其他",
    "text": "文本题",
    "select": "选择题",
    "rating": "评分题",
    "bedeck": "其他",
    "matrix": "表格题",
    "mycollect": "我的收藏",
  },
  "ed": {
    "survey": "调查问卷",
    "editSurvey": "修改",
    "addNewPage": "添加新页面",
    "deletePage": "删除页面",
    "editPage": "编辑页面",
    
    "newPageName": "页面",
    "newQuestionName": "Q",
    "newItemText": "选项",
    "newPanelName": "面板",
   
    "testSurveyAgain": "再次预览问卷",
    "testSurveyWidth": "问卷宽度:",
   
    "saveSurvey": "保存问卷",

    "generalize": "问卷概括",
    "designer": "编辑问卷",
    "testSurvey": "预览问卷",
    "theme": "外观设置",
    "issue": "发布设置",
    "analyze": "数据分析",
    "datams": "数据管理",


    "embedSurvey": "问卷嵌入",

    "translation": "导入导出",
    "jsonEditor": "JSON 编辑器",
    "undo": "撤销",
    "redo": "恢复",
    "options": "选项",
    "generateValidJSON": "生成 JSON 数据",
    "generateReadableJSON": "生成易读的 JSON 数据",
    "toolbox": "工具箱",
    "delSelObject": "删除所选对象",
    "editSelObject": "编辑所选对象",
    "correctJSON": "请修正 JSON 数据",
    "surveyResults": "问卷结果:",
    "modified": "已修改",
    "saving": "保存中...",
    "saved": "已保存",
    "defaultLocale": "默认 ({0})",
    "settings": "问卷设置",
    "moveRight": "下一页",
    "moveLeft": "上一页",
    "otherItemText": "其他",
    "edit": "编辑",
    
    "surveyResultsTable": "As Table",
    "surveyResultsJson": "As JSON",
    "resultsTitle": "Question Title",
    "resultsName": "Question Name",
    "resultsValue": "Answer Value",
    "resultsDisplayValue": "Display Value",
    "saveError": "Error! Editor content is not saved.",
    "translationAddLanguage": "选择要翻译的语言",
    "translationShowAllStrings": "显示所有字符",
    "translationShowAllPages": "显示所有页面",
    "translationNoStrings": "No strings to translate. Please, change the filter.",
    "translationExportToSCVButton": "导出CSV",
    "translationImportFromSCVButton": "导入CSV",
    "translationMergeLocaleWithDefault": "Merge {0} with default locale",
    lg: {
      //Logic tab strings
      page_visibilityName: "页面可见",
      panel_visibilityName: "面板可见",
      panel_enableName: "面板只读/可写",
      question_visibilityName: "问题可见",
      question_enableName: "问题只读/可写",
      question_requireName: "问题必答条件",
      trigger_completeName: "提交问卷",
      trigger_setvalueName: "设置问题值",
      trigger_copyvalueName: "复制问题值",
      trigger_skipName: "跳过问题",
      trigger_runExpressionName: "运行自定义逻辑表达式",
      completedHtmlOnConditionName: "Custom 'Thank you page' text",

      page_visibilityDescription:"使页面在逻辑表达式正确时可见，否则就看不见",
      panel_visibilityDescription:"使面板在逻辑表达式正确时可见，否则就让它隐藏",
      panel_enableDescription:"使面板及其内部的所有元素在逻辑表达式正确时启用。否则就让他们只读",
      question_visibilityDescription:"使问题在逻辑表达式正确时可见。否则就看不见",
      question_enableDescription:
        "使问题在逻辑表达式正确时启用。否则保持禁用状态。",
      question_requireDescription:
        "当逻辑表达式正确时，就需要提问。",
      trigger_completeDescription:
        "当逻辑表达式正确时，调查将完成，最终用户将看到“感谢页面”。",
      trigger_setvalueDescription:
        "当逻辑表达式中使用的问题值更改并且逻辑表达式正确时，该值将设置为所选问题。",
      trigger_copyvalueDescription:
        "当逻辑表达式中使用的问题值更改且逻辑表达式正确时，则将一个选定问题的值复制到另一个选定问题。",
      trigger_skipDescription:
        "当逻辑表达式正确时，调查将跳到/聚焦所选问题。",
      trigger_runExpressionDescription:
        "当逻辑表达式正确时，将执行自定义表达式。您可以选择将此表达式结果设置为选定的问题",
      completedHtmlOnConditionDescription:
        "如果逻辑表达式正确，则“感谢页面”的默认文本将更改为给定文本。",

      itemExpressionText: "当表达式: '{0}' 正确时:", //{0} - the expression
      page_visibilityText: "页面 {0} 可见", //{0} page name
      panel_visibilityText: "面板 {0} 可见", //{0} panel name
      panel_enableText: "面板 {0} enable", //{0} panel name
      question_visibilityText: "问题 {0} 可见", //{0} question name
      question_enableText: "问题 {0} enable", //{0} question name
      question_requireText: "问题 {0} required", //{0} question name
      trigger_completeText: "问卷提交",
      trigger_setvalueText: "Set into question: {0} value {1}", //{0} question name, {1} setValue
      trigger_copyvalueText: "Copy into question: {0} value from question {1}", //{0} and {1} question names
      trigger_skipText: "Survey skip to the question {0}", //{0} question name
      trigger_runExpressionText1: "运行表达式: '{0}'", //{0} the expression
      trigger_runExpressionText2: " and set it's result into question: {0}", //{0} question name
      completedHtmlOnConditionText:
        "显示自定义提交成功页面",

      expressionEditorTitle: "设置逻辑表达式",

      deleteOperation: "删除逻辑",
      addNewOperation: "添加新逻辑",
      expressionInvalid: "逻辑表达式为空或无效。请改正一下.",
      noOperationError: "请至少添加一个操作.",
      operationInvalid: "请修复逻辑中的问题."
    }
  },
  "pel": {"isRequired": "必答"},
  "pe": {
    "apply": "应用",
    "ok": "确定",
    "cancel": "取消",
    "reset": "重置",
    "close": "关闭",
    "delete": "删除",
    "addNew": "新建",
    "removeAll": "全部删除",
    "edit": "编辑器",
    "empty": "<空>",
    "fastEntry": "批量增加",
    "formEntry": "选项",
    "testService": "测试服务",
    "editChoices": "编辑选择",
    "showMore": "更多细节请查看文档",
    "conditionHelp": "请输入一个布尔表达式。当布尔值为真，问题/页面可见。例如：{question1} = 'value1' or ({question2} * {question4}  > 20 and {question3} < 5)",
    "expressionHelp": "请输入一项条件判断。当条件判断为真时问题/页面将可见。例如: {question1} = 'value1' or ({question2} = 3 and {question3} < 5)",
    "propertyIsEmpty": "值不能为空",
    "propertyIsLegal": "值应该为数字",
    "value": "值",
    "text": "矩阵行",
    "columnEdit": "编辑列: {0}",
    "itemEdit": "编辑选项: {0}",
    "hasOther": "添加「其他」项",
    "otherText": "其他文本",
    "url": "URL",
    "path": "路径",
    "valueName": "变量名",
    "titleName": "变量标题",
    "name": "题目名",
    "title": "题目文本",
    "inputWidth": "输入框宽度",
    "inputSuffix": "输入框后缀",
    "cellType": "单元格类型",
 
    "colCount": "列数",
    "choicesOrder": "设置选项顺序",
    "visible": "可见",
    "isRequired": "必答",
    "startWithNewLine": "问题是否新起一行?",
    "rows": "文本框行数",
    "placeHolder": "占位文本",
    "showPreview": "是否显示图像预览?",
    "storeDataAsText": "以 JSON 文本方式存储文件",
    "maxSize": "文件最大尺寸 (Bytes)",
    "imageHeight": "图片高度",
    "imageWidth": "图片宽度",
    "rowCount": "默认行数",
    "addRowText": "添加条目按钮文本",
    "removeRowText": "删除条目按钮文本",
    "minRateDescription": "最小值提示",
    "maxRateDescription": "最大值提示",
    "defaultValue": "默认值",
    "inputType": "文本框类型",
    "optionsCaption": "下拉框提示语",
    "qEditorTitle": "编辑问题: {0}",
    "showTitle": "显示标题",
    "locale": "默认语言",
    "mode": "模式 (编辑/只读)",
    "clearInvisibleValues": "清除隐藏值",
    "cookieName": "Cookie禁止填答两次",
    "progressBarType": "进度显示类型",
    "questionDescriptionLocation": "说明位置",
    "focusOnFirstError": "聚焦第一个错误问题",
    "loadAnswerData": "续填方式",
    "award": "答题奖励",
    "sendResultOnPageNext": "下一页提交",
    "storeOthersAsComment": "将“其他”值存储在单独的字段中",
    "showPageTitles": "显示页面标题",
    "showPageNumbers": "显示页数",
    "pagePrevText": "前一页按钮文本",
    "pageNextText": "后一页按钮文本",
    "timerSpentAll": "1111 {0} on this page and {1} in total.",
    "completeText": "完成按钮文本",
    "startSurveyText": "开始按钮文本",
    "showNavigationButtons": "显示导航按钮 (默认导航)",
    "showPrevButton": "返回至上一页",
    "firstPageIsStarted": "调查的第一页面为起始页.",
    "showCompletedPage": "结尾展示完成后的页面 (completedHtml)",
    "goNextPageAutomatic": "自动跳转",
    "showProgressBar": "进度条",
    "questionTitleLocation": "问题的标题位置",
    "requiredText": "必答符号",
    "questionStartIndex": "问题起始标志 (1, 2 或 'A', 'a')",
    "showQuestionNumbers": "显示问题编号",
    "questionTitleTemplate": "问题标题模板{no}. {require} {title}",
    "questionErrorLocation": "问题错误定位",
    "focusFirstQuestionAutomatic": "改变页面时聚焦在第一个问题",
    "questionsOrder": "问题在页面上的顺序",
    "maxTimeToFinish": "完成调查的最长时间",
    "maxTimeToFinishPage": "完成调查中页面的最长时间",
    "showTimerPanel": "显示计时器面板",
    "showTimerPanelMode": "显示计时器面板模式",
    "renderMode": "渲染模式",
    "allowAddPanel": "允许添加面板",
    "allowRemovePanel": "允许删除面板",
    "panelAddText": "添加面板文本",
    "panelRemoveText": "删除面板文本",
    "isSinglePage": "一个页面显示所有题目",
    "tabs": {
      "general": "通用",
      "items": "选项",
      "templateTitle": "模板标题",
      "navigation": "导航",
      "question": "问题",
      "completedHtml": "完成后的Html",
      "loadingHtml": "加载中的Html",
      "timer": "问卷计时器",
      "triggers": "触发器",
      "fileOptions": "选项",
      "html": "HTML 编辑器",
      "columns": "设置列",
      "rows": "设置行",
      "choices": "选项",
      "visibleIf": "可见条件",
      "enableIf": "激活条件",
      "rateValues": "设置评分值",
      "choicesByUrl": "URL 导入选项",
      "matrixChoices": "默认选项",
      "multipleTextItems": "文本输入",
      "validators": "校验规则"
    },
    "editProperty": "编辑属性: '{0}'",
    "items": "[数量:{0}]",
    "enterNewValue": "请设定值",
    "noquestions": "问卷中还没有创建任何问题",
    "createtrigger": "请创建触发器",
    "triggerOn": "当",
    "triggerMakePagesVisible": "使页面可见:",
    "triggerMakeQuestionsVisible": "使问题可见:",
    "triggerCompleteText": "如果满足条件，则完成问卷",
    "triggerNotSet": "触发器尚未设置",
    "triggerRunIf": "满足下列条件时执行",
    "triggerSetToName": "修改下列问题值:",
    "triggerSetValue": "修改为:",
    "triggerIsVariable": "在问卷提交结果中不要包含该变量",
    "addItem": "Click to add an item...",
    "itemValueEdit": "显示条件",
    "move": "Move",
    "notEmpty": "<edit value>",
    "conditionSelectQuestion": "选择问题",
    "conditionValueQuestionTitle": "Please enter/select the value",
    "conditionButtonAdd": "Add",
    "conditionButtonReplace": "Replace",
    "aceEditorHelp": "按ctrl+空格得到表达式完成提示",
    "aceEditorRowTitle": "Current row",
    "aceEditorPanelTitle": "Current panel",
    "conditionShowMoreUrl": "https://www.zkey.cc/",
    "assistantTitle": "Available questions:",
    "cellsEmptyRowsColumns": "There is should be at least one column or row",
    "rowid": "Row ID",
    "imageLink": "Image Link",
    "columnLayout": "Columns layout",
    "addRowLocation": "Add row button location",
    "cellsDefaultRow": "Default cells texts",
    "surveyEditorTitle": "设置问卷",
    "maxLength": "Maximum length",
    "triggerFromName": "Copy value from:",
    "triggerRunExpression": "运行这个表达式:"
  },
  "op": {
    "empty": "为空",
    "notempty": "不为空",
    "equal": "等于",
    "notequal": "不等于",
    "contains": "包含",
    "notcontains": "不包含",
    "greater": "大于",
    "less": "小于",
    "greaterorequal": "大于等于",
    "lessorequal": "小于等于"
  },
  "ew": {
    "angular": "使用 Angular 时",
    "jquery": "使用 JQuery 时",
    "knockout": "使用 Knockout 时",
    "react": "使用 React 时",
    "vue": "使用 Vue 时",
    "bootstrap": "使用 Bootstrap 时",
    "standard": "不使用 Bootstrap 时",
    "showOnPage": "嵌入页面显示",
    "showInWindow": "使用单独的问卷窗口",
    "loadFromServer": "从服务器加载问卷 JSON 数据",
    "titleScript": "脚本和样式",
    "titleHtml": "HTML",
    "titleJavaScript": "JavaScript"
  },
  "validators": {
    "answercountvalidator": "数量检查",
    "emailvalidator": "邮箱",
    "numericvalidator": "数字",
    "regexvalidator": "正则表达式",
    "textvalidator": "文本",
    "expressionvalidator": "表达式验证"
  },
  "triggers": {
    "completetrigger": "完成问卷",
    "setvaluetrigger": "设置问题值",
    "visibletrigger": "修改可见性",
    "copyvaluetrigger": "复制值",
    "runexpressiontrigger": "表达式"
  },
  "p": {
    "radioStyle": "单选按钮样式",
    "checkboxStyle": "多选按钮样式",
    "commentText": "备注文本",
    "useDisplayValuesInTitle": "引用变量用文本",
    "hideTitleNo": "隐藏题号",
    "choices": "选项",
    "choicesByUrl": "URL 导入选项",
    "hideIfChoicesEmpty": "选项为空隐藏",
    "renderAs": "输出样式",
    "requiredIf": "必答条件",
    "allowClear": "允许清除",
    "height": "高度",
    "inputWidth": "文本框宽度",
    "inputSuffix": "文本框后缀",
    "choicesOrder": "选项排序",
    "colCount": "列数",
    "correctAnswer": "正确答案",
    "defaultVaule": "默认选项",
    "description": "说明",
    "enableIf": "允许判断",
    "hasComment": "评语",
    "hasOther": "其他",
    "showClearButton": "显示清除按钮",
    "selectAllText": "全选文本",
    "hasSelectAll": "全选",
    "otherText": "其他文本",
    "otherRequired": "其他必答",
    "page": "所在页面",
    "readOnly": "只读",
    "indent": "缩进",
    "isRequired": "必答",
    "requiredErrorText": "必答错误提示",
    "otherErrorText": "其他错误提示",
    "startWithNewLine": "允许问题在新行",
    "paddingLeft": "左边距",
    "paddingRight": "右边距",
    "paddingTop": "上边距",
    "paddingBottom": "下边距",
    "contentPaddingLeft": "内容左缩进",
    "rowsVisibleIf": "行显示条件",
    "columnsVisibleIf": "列显示条件",
    "radioClass": "按钮样式",
    "checkboxClass": "按钮样式",
    "showTitle": "显示标题",
    "locale": "默认语言",
    "underpainting": "页面背景色",
    "typePageUnderpainting": "版心背景色",
    "background": "页面背景图",
    "typePageBackground": "版心背景图",
    "userName": "登录账号",
    "loginType": "登录类型",
    "oneToOne": "一对一",
    "remind": "多次填答提醒",
    "loginErrorText": "登录失败提示",
    "getUrlArguments": "获取URL参数",
    "areaWidth": "版心宽度",
    "passWord": "登录密码",
    "surveyTheme": "主题",
    "showQuestionNo":"显示标题",
    "copyrightHtml":"版权文本",
    "clearable":"可清空",
    "prefixIcon":"头部图标",
    "suffixIcon":"尾部图标",
    "inputSize":"尺寸",
    "showCopyright":"版权",
    "otherPlaceHolder":"其他占位文本",
    "descriptionLocation":"说明位置",
    "choicesMax":"选项最大值",
    "choicesMin":"选项最小值",
    "choicesStep":"步长",
    "filterable":"搜索",
    "multiple":"多选",
    "showOptionsCaption":"显示选择标题",
    "multiSelect":"多选",
    "contentMode":"多选",
    "rowsOrder":"行随机",


    "mode": "模式 (编辑/只读)",
    "clearInvisibleValues": "清除隐藏值",
    "cookieName": "Cookie禁止填答两次",
    "progressBarType": "进度显示类型",
    "questionDescriptionLocation": "说明位置",
    "focusOnFirstError": "聚焦第一个错误问题",
    "calculatedValues": "推测值",
    "completedHtmlOnCondition": "推测值提交页面",

    "loadAnswerData": "续填方式",
    "award": "答题奖励",
    "sendResultOnPageNext": "下一页提交",
    "storeOthersAsComment": "将“其他”值存储在单独的字段中",
    "showPageTitles": "显示页面标题",
    "showPageNumbers": "显示页数",
    "pagePrevText": "前一页按钮文本",
    "pageNextText": "后一页按钮文本",
    "maxTextLength":"文本最大长度",
    "maxOthersLength":"其它选项最大长度",
    "completeText": "完成按钮文本",
    "startSurveyText": "开始按钮文本",
    "showNavigationButtons": "显示导航按钮",
    "showPrevButton": "显示前一页按钮",
    "firstPageIsStarted": "调查的第一页面为起始页.",
    "showCompletedPage": "提交展示完成后的页面",
    "goNextPageAutomatic": "自动跳转",
    "showProgressBar": "显示问卷进度",
    "showPageProgressBar": "显示页进度",
    "questionTitleLocation": "问题的标题位置",
    "requiredText": "必答符号",
    "questionStartIndex": "问题起始标志 (1, 2 或 'A', 'a')",
    "showQuestionNumbers": "显示问题编号",
    "questionTitleTemplate": "问卷标题模板{no}. {require} {title}",
    "questionErrorLocation": "问题错误定位",
    "focusFirstQuestionAutomatic": "聚焦第一个问题",
    "questionsOrder": "问题顺序",
    "maxTimeToFinish": "完成调查的最长时间",
    "maxTimeToFinishPage": "完成调查中页面的最长时间",
    "showTimerPanel": "显示计时器面板",
    "showTimerPanelMode": "显示计时器面板模式",
    "renderMode": "渲染模式",
    "allowAddPanel": "允许添加面板",
    "allowRemovePanel": "允许删除面板",
    "panelAddText": "添加面板文本",
    "panelRemoveText": "删除面板文本",
    "isSinglePage": "一个页面显示所有题目",
    "name": "题目名",
    "title": {"name": "标题", "title": "如果与名字相同，请设置为空值"},
    "survey_title": {"name": "标题", "title": "问卷标题在每页上都会显示"},
    "page_title": {"name": "标题", "title": "页面标题"},
    "navigationButtonsVisibility": "导航栏按钮可见性",
    "isLogin": "登录页",
    "visible": "可见",
    "visibleIf": "可见条件",
    "state": "状态",
    "innerIndent": "内缩进",
    "width": "宽度",
    "valueName": "变量名",
    "defaultValue": "默认值",
    "validators": "验证",
    "titleLocation": "问题的标题位置",
    "label": "标签",
    "valueTrue": "值为True",
    "valueFalse": "值为False",
    "cols": "列",
    "rows": "行",
    "placeHolder": "占位文本",
    "optionsCaption": "选择标题",
    "expression": "表达式",
    "format": "版式",
    "displayStyle": "展示风格",
    "currency": "currency",
    "useGrouping": "用户组",
    "showPreview": "显示预览",
    "allowMultiple": "可选",
    "imageHeight": "图片高度",
    "imageWidth": "图片宽度",
    "imageFit": "图片适应",
    "showLabel": "显示标签",
    "choicesEnableIf": "隐藏条件",
    "choicesVisibleIf": "显示条件",
    "storeDataAsText": "将数据存储为文本",
    "maxSize": "最大尺寸",
    "html": "HTML",
    "cells": "单元格",
    "isAllRowRequired": "所有行答",
    "horizontalScroll": "横轴",
    "cellType": "单元格类型",
    "columnsLayout": "列布局",
    "columnColCount": "一行几列",
    "columnMinWidth": "最小列宽",
    "defaultValueFromLastRow": "最后一行提交",
    "columnLayout": "布局方式",
    "mobileType": "移动端显示",
    "showHeader": "显示表头",
    "rowCount": " 行数",
    "minRowCount": "最小行数",
    "maxRowCount": "最大行数",
    "keyName": "键名",
    "keyDuplicationError": "这个值应该是惟一的",
    "confirmDelete": "删除前是否确认",
    "confirmDeleteText": "确认删除文本",
    "addRowLocation": "添加行位置",
    "addRowText": "行文本添加",
    "removeRowText": "行文本移除",
    "items": "选项",

    "itemSize": "选项数",
    "templateTitle": "模板名称",
    "templateDescription": "模板描述",
    "panelCount": "面板数",
    "minPanelCount": "最小面板数",
    "maxPanelCount": "最大面板数",
    "panelsState": "面板状态",
    "panelPrevText": "面板上一文本",
    "panelNextText": "面板下一文本",
    "showRangeInProgress": "显示前进范围",
    "templateTitleLocation": "模板问题的标题位置",
    "rateValues": "设置评分值",
    "rateMin": "最小值",
    "rateMax": "最大值",
    "rateStep": "梯级",
    "minRateDescription": "最小梯级描述",
    "maxRateDescription": "最大梯级描述",
    "inputType": "文本框类型",
    "size": "文本框宽度",
    "completedHtml": "完成的Html",
    "repeatedHtml": "多次填答Html",
    "completedBeforeHtml": "完成之前的Html",
    "loadingHtml": "加载中的Html",
    "triggers": "触发器",
    "checkErrorsMode": "错误提示",
    "defaultPanelValue": "默认面板值",
    "defaultRowValue": "默认行值",
    "hasNone": "排他",
    "noneText": "排他文本",
    "text": "text",
    "minValue": "最小值",
    "maxValue": "最大值",
    "minLength": "最小长度",
    "maxLength": "最大长度",
    "allowDigits": "允许数字",
    "minCount": "最小数",
    "maxCount": "最大数",
    "regex": "正则表达式",

    // 滑块题
    "range": "范围选择",
    "vertical": "竖向模式",
    "showInput": "输入框",
    "showInputControls": "输入框按钮",
    "inputBoxSize": "输入框尺寸",
    "showTooltip": "提示工具",
    "showStops": "间断点",

    // 星星题
    "voidIconClass": "图标",
    "allowHalf": "半选",
    "colors": "颜色",
    "disabledVoidColor": "只读时未选中颜色",
    "highThreshold": "高界限值",
    "lowThreshold": "低界限值",
    "max": "最大值",
    "scoreTemplate": "值模板",
    "showScore": "值显示",
    "showText": "辅助文字",
    "textColor": "辅助文字颜色",
    "texts": "辅助文字数组",
    "voidColor": "未选中颜色",
    "reeaeaea":""
  },
  "pv": {
    "defaultTheme": "默认主题",
    "schoolTheme": "学校主题",
    "examinationTheme": "考试主题",
    "festivalTheme": "节日主题",
    "bjbysTheme": "学生就业主题",
    "iradio_minimal":"简约",
    "iradio_minimal-red":"简约-红",
    "iradio_minimal-green":"简约-绿",
    "iradio_minimal-blue":"简约-深蓝",
    "iradio_minimal-aero":"简约-浅蓝",
    "iradio_minimal-grey":"简约-灰",
    "iradio_minimal-orange":"简约-橙",
    "iradio_minimal-yellow":"简约-黄色",
    "iradio_minimal-pink":"简约-粉",
    "iradio_minimal-purple":"简约-紫",
    "iradio_square":"直角",
    "iradio_square-red":"直角-红",
    "iradio_square-green":"直角-绿",
    "iradio_square-blue":"直角-深蓝",
    "iradio_square-aero":"直角-浅蓝",
    "iradio_square-grey":"直角-灰",
    "iradio_square-orange":"直角-橙",
    "iradio_square-yellow":"直角-黄色",
    "iradio_square-pink":"直角-粉",
    "iradio_square-purple":"直角-紫",
    "iradio_flat":"圆角",
    "iradio_flat-red":"圆角-红",
    "iradio_flat-green":"圆角-绿",
    "iradio_flat-blue":"圆角-深蓝",
    "iradio_flat-aero":"圆角-浅蓝",
    "iradio_flat-grey":"圆角-灰",
    "iradio_flat-orange":"圆角-橙",
    "iradio_flat-yellow":"圆角-黄色",
    "iradio_flat-pink":"圆角-粉",
    "iradio_flat-purple":"圆角-紫",
    "iradio_futurico":"极化",
    "iradio_polaris":"未来",
    "icheckbox_minimal":"简约",
    "icheckbox_minimal-red":"简约-红",
    "icheckbox_minimal-green":"简约-绿",
    "icheckbox_minimal-blue":"简约-深蓝",
    "icheckbox_minimal-aero":"简约-浅蓝",
    "icheckbox_minimal-grey":"简约-灰",
    "icheckbox_minimal-orange":"简约-橙",
    "icheckbox_minimal-yellow":"简约-黄色",
    "icheckbox_minimal-pink":"简约-粉",
    "icheckbox_minimal-purple":"简约-紫",
    "icheckbox_square":"直角",
    "icheckbox_square-red":"直角-红",
    "icheckbox_square-green":"直角-绿",
    "icheckbox_square-blue":"直角-深蓝",
    "icheckbox_square-aero":"直角-浅蓝",
    "icheckbox_square-grey":"直角-灰",
    "icheckbox_square-orange":"直角-橙",
    "icheckbox_square-yellow":"直角-黄色",
    "icheckbox_square-pink":"直角-粉",
    "icheckbox_square-purple":"直角-紫",
    "icheckbox_flat":"圆角",
    "icheckbox_flat-red":"圆角-红",
    "icheckbox_flat-green":"圆角-绿",
    "icheckbox_flat-blue":"圆角-深蓝",
    "icheckbox_flat-aero":"圆角-浅蓝",
    "icheckbox_flat-grey":"圆角-灰",
    "icheckbox_flat-orange":"圆角-橙",
    "icheckbox_flat-yellow":"圆角-黄色",
    "icheckbox_flat-pink":"圆角-粉",
    "icheckbox_flat-purple":"圆角-紫",
    "icheckbox_futurico":"极化",
    "icheckbox_polaris":"未来",
   
    "anonymous": "公开问卷",
    "select": "账号密码登录",
    "telLogin": "手机验证码无样本登录",
    "telSampleLogin": "手机验证码有样本登录",
    "passwordLogin": "密码登录",
    "urlLogin": "URL登录",
    "separateTable": "分表",
    "separateRow": "分行",
    "selectToDropdown": "选择转下拉",
    "noChange": "不变化",
    "radioToSelect": "单选转下拉",
    "local": "本地加载",
    "redEnvelope": "红包奖励",
    "systemPresent": "系统奖励",
    "userPresent": "自定义奖励",

    "true": "true",
    "false": "false",
    "inherit": "继承问卷设置",
    "noneclear": "不清除",
    "show": "显示",
    "hide": "隐藏",
    "default": "默认",
    "initial": "初始",
    "random": "随机",
    "collapsed": "collapsed",
    "expanded": "扩充",
    "none": "无",
    "asc": "升序",
    "desc": "降序",
    "indeterminate": "模糊",
    "decimal": "小数",
    "currency": "货币",
    "percent": "百分数",
    "firstExpanded": "第一个扩展",
    "off": "关闭",
    "both": "上部和下部",
    "onPanel": "在面板上",
    "onSurvey": "在问卷上",
    "list": "列表",
    "progressTop": "进度条顶部",
    "progressBottom": "进度条底部",
    "progressTopBottom": "进度条顶部底部",
    "horizontal": "水平",
    "vertical": "垂直",
    "top": "上部",
    "bottom": "下部",
    "topBottom": "上部和下部",
    "left": "左",
    "color": "颜色",
    "date": "年月日",
    "datetime": "日期时间",
    "datetime-local": "本地时间",
    "email": "邮箱",
    "month": "年月",
    "number": "数字",
    "password": "密码",
    "range": "范围",
    "tel": "手机",
    "text": "文本",
    "time": "时间",
    "url": "url地址",
    "week": "年周",
    "hidden": "隐藏",
    "on": "打开",
    "onPage": "按页",
    "edit": "编辑",
    "display": "显示",
    "onComplete": "清除隐藏值",
    // "onComplete": "保留值提交清除",
    // "onHidden": "不保留值提交清除",
    "all": "所有",
    "page": "页",
    "survey": "问卷",
    "onNextPage": "下一页",
    "onValueChanged": "值变化"
    
  },
  "ts": {
    "selectPage": "选择要测试的页面:",
    "showInvisibleElements": "显示隐藏题目"
  },
  "zkey":{ 
    "classifyLocale":"默认语言",
    "background":"背景", 
    "typePageBackground":"版心背景", 
    "auxiliaryPage":"辅助页", 
    "button":"按钮"
  }
};
//Uncomment this line on creating a translation file. You should replace "en" and enStrings with your locale ("fr", "de" and so on) and your variable.
//editorLocalization.locales["en"] = enStrings;
