/* Automatically generated by './build/bin/build-entry.js' */
import ActionConvert from './ActionConvert/index.js';
import SurveyEditor from './SurveyEditor/index.js';
import ActionSeparator from './ActionSeparator/index.js';
import ActionShowPropertyGrid from './ActionShowPropertyGrid/index.js';
import DesignerContainer from './DesignerContainer/index.js';
import JsonEitor from './JsonEditor/index.js';
import PropertyEditor from './PropertyEditor/PropertyEditor/index.js';
import PropertyEditorBoolean from './PropertyEditor/PropertyEditorBoolean/index.js';
import PropertyEditorCells from './PropertyEditor/PropertyEditorCells/index.js';
import PropertyEditorCellsContent from './PropertyEditor/PropertyEditorCellsContent/index.js';
import PropertyEditorCondition from './PropertyEditor/PropertyEditorCondition/index.js';
import PropertyEditorCustom from './PropertyEditor/PropertyEditorCustom/index.js';
import PropertyEditorCustomContent from './PropertyEditor/PropertyEditorCustomContent/index.js';
import PropertyEditorDropdown from './PropertyEditor/PropertyEditorDropdown/index.js';
import PropertyEditorError from './PropertyEditor/PropertyEditorError/index.js';
import PropertyEditorExpression from './PropertyEditor/PropertyEditorExpression/index.js';
import PropertyEditorExpressionContent from './PropertyEditor/PropertyEditorExpressionContent/index.js';
import PropertyEditorHtml from './PropertyEditor/PropertyEditorHtml/index.js';
import PropertyEditorHtmlContent from './PropertyEditor/PropertyEditorHtmlContent/index.js';
import PropertyEditorItemvaluesContent from './PropertyEditor/PropertyEditorItemvaluesContent/index.js';
import PropertyEditorModal from './PropertyEditor/PropertyEditorModal/index.js';
import PropertyEditorModalContent from './PropertyEditor/PropertyEditorModalContent/index.js';
import PropertyEditorMultiplevalues from './PropertyEditor/PropertyEditorMultiplevalues/index.js';
import PropertyEditorNestedContent from './PropertyEditor/PropertyEditorNestedContent/index.js';
import PropertyEditorNesteditems from './PropertyEditor/PropertyEditorNesteditems/index.js';
import PropertyEditorNesteditemsContent from './PropertyEditor/PropertyEditorNesteditemsContent/index.js';
import PropertyEditorNumber from './PropertyEditor/PropertyEditorNumber/index.js';
import PropertyEditorOneselected from './PropertyEditor/PropertyEditorOneselected/index.js';
import PropertyEditorOneselectedContent from './PropertyEditor/PropertyEditorOneselectedContent/index.js';
import PropertyEditorRestfull from './PropertyEditor/PropertyEditorRestfull/index.js';
import PropertyEditorRestfullContent from './PropertyEditor/PropertyEditorRestfullContent/index.js';
import PropertyEditorString from './PropertyEditor/PropertyEditorString/index.js';
import PropertyEditorSwitch from './PropertyEditor/PropertyEditorSwitch/index.js';
import PropertyEditorText from './PropertyEditor/PropertyEditorText/index.js';
import PropertyEditorTextContent from './PropertyEditor/PropertyEditorTextContent/index.js';
import PropertyEditorTriggersitems from './PropertyEditor/PropertyEditorTriggersitems/index.js';
import PropertyEditorValue from './PropertyEditor/PropertyEditorValue/index.js';
import PropertyEditorValueContent from './PropertyEditor/PropertyEditorValueContent/index.js';
import GridPropertyEditor from './QuestionEditor/GridPropertyEditor/index.js';
import QuestionEditor from './QuestionEditor/QuestionEditor/index.js';
import QuestionEditorContent from './QuestionEditor/QuestionEditorContent/index.js';
import QuestionEditorPropertyGrid from './QuestionEditor/QuestionEditorPropertyGrid/index.js';
import QuestionEditorPropertyGridContent from './QuestionEditor/QuestionEditorPropertyGridContent/index.js';
import QuestionEditorTab from './QuestionEditor/QuestionEditorTab/index.js';
import QuestionEditorTabTemplate from './QuestionEditor/QuestionEditorTabTemplate/index.js';
import PropertyGrid from './PropertyGrid/index.js';
import PropertyGridHeader from './PropertyGridHeader/index.js';
import SurveyAttach from './SurveyAttach/index.js';
import SurveyEmbeding from './SurveyEmbeding/index.js';
import SurveyEmpty from './SurveyEmpty/index.js';
import SurveyLive from './SurveyLive/index.js';
import SurveyLiveResultTableRow from './SurveyLiveResultTableRow/index.js';
import SurveyLiveSimulator from './SurveyLiveSimulator/index.js';
import SurveyLiveTab from './SurveyLiveTab/index.js';
import SurveyManage from './SurveyManage/index.js';
import SurveyTest from './SurveyTest/index.js';
import Toolbar from './Toolbar/index.js';
import ToolbarButton from './ToolbarButton/index.js';
import ToolbarHeader from './ToolbarHeader/index.js';
import ToolbarOptions from './ToolbarOptions/index.js';
import ToolbarPagesEditor from './ToolbarPagesEditor/index.js';
import ToolbarState from './ToolbarState/index.js';
import Toolbox from './Toolbox/index.js';
import Translation from './Translation/index.js';
import TranslationGroup from './TranslationGroup/index.js';
import TabDesigner from './TabDesigner/index.js';
import TabTest from './TabTest/index.js';
import TabJson from './TabJson/index.js';

const components = [
  SurveyEditor, 
  TabDesigner, 
  TabTest, 
  TabJson, 
  ActionConvert,
  ActionSeparator,
  ActionShowPropertyGrid,
  DesignerContainer,
  JsonEitor,
 
  PropertyEditor,
  PropertyEditorBoolean,
  PropertyEditorCells,
  PropertyEditorCellsContent,
  PropertyEditorCondition,
  PropertyEditorCustom,
  PropertyEditorCustomContent,
  PropertyEditorDropdown,
  PropertyEditorError,
  PropertyEditorExpression,
  PropertyEditorExpressionContent,
  PropertyEditorHtml,
  PropertyEditorHtmlContent,
  PropertyEditorItemvaluesContent,
  PropertyEditorModal,
  PropertyEditorModalContent,
  PropertyEditorMultiplevalues,
  PropertyEditorNestedContent,
  PropertyEditorNesteditems,
  PropertyEditorNesteditemsContent,
  PropertyEditorNumber,
  PropertyEditorOneselected,
  PropertyEditorOneselectedContent,
  PropertyEditorRestfull,
  PropertyEditorRestfullContent,
  PropertyEditorString,
  PropertyEditorSwitch,
  PropertyEditorText,
  PropertyEditorTextContent,
  PropertyEditorTriggersitems,
  PropertyEditorValue,
  PropertyEditorValueContent,
  GridPropertyEditor,
  QuestionEditor,
  QuestionEditorContent,
  QuestionEditorPropertyGrid,
  QuestionEditorPropertyGridContent,
  QuestionEditorTab,
  QuestionEditorTabTemplate,
  PropertyGrid,
  PropertyGridHeader,
  QuestionEditorPropertyGrid,
  SurveyAttach,
  SurveyEmbeding,
  SurveyEmpty,
  SurveyLive,
  SurveyLiveResultTableRow,
  SurveyLiveSimulator,
  SurveyLiveTab,
  SurveyManage,
  SurveyTest,
  Toolbar,
  ToolbarButton,
  ToolbarHeader,
  ToolbarOptions,
  ToolbarPagesEditor,
  ToolbarState,
  Toolbox,
  Translation,
  TranslationGroup
]


const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}
export default {
  version: '2.13.0',
  install,
  components
};
